# Generated by Django 4.1.5 on 2023-02-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_lot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
