# Generated by Django 4.1.5 on 2023-02-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_lot_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='category',
            field=models.CharField(blank=True, choices=[(None, 'No category'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Home', 'Home'), ('Toys', 'Toys'), ('Art', 'Art')], max_length=100),
        ),
    ]
