# Generated by Django 4.1.5 on 2023-02-07 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_lot_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
